#!/bin/bash
#
# This a helper script fo this
# conatiner to build and run
#
# Author: Philip Bergman <philip@zicht.nl>

# enable clients connect from any host
xhost +

ID="zicht/keepass"
TAG="1.0"
CONTAINER_NAME="${ID//[!a-zA-Z0-9]/_}_${TAG//[!a-zA-Z0-9]/_}"
DATABASE_LOCATION=/home/philip/NetworkShares/zon/projecten/ZZtechniek_techniek/KeePass/
CONTAINER=$(sudo docker ps -a | grep ${CONTAINER_NAME})

if [[ -z "$CONTAINER" ]]; then
    echo "Starting conatiner"
    sudo docker run -v "/tmp/.X11-unix:/tmp/.X11-unix" \
                    -v "$DATABASE_LOCATION:/home/keepass/database/" \
                    -e "DISPLAY=unix$DISPLAY" \
                    --name "${CONTAINER_NAME}" \
                    -it "docker-register:5000/${ID}:${TAG}" /bin/bash
else
    if [[ "$(echo "${CONTAINER}" | grep -E 'Up\s[0-9]+\s[minutes|hours|days|years]')" ]]; then
        IP=$(sudo docker inspect -f '{{ .NetworkSettings.IPAddress }}' ${CONTAINER_NAME});
        echo -e "${ID}:${TAG} is allready running \e[32m${IP}\e[0m";
     else
        sudo docker start --attach=true --interactive=true "${CONTAINER_NAME}"
    fi

fi


